export default [
  {
    inspectionStatus: { value: "OPEN", style: "color: #007bff; font-weight: bold;" },
    inspectionId: { value: "INS-125", style: "color: #28a745; text-decoration: underline;" },
    lotStatusVerdict: { value: "PENDING", style: "background-color: #ffc107; padding: 2px 5px; border-radius: 3px;" },
    icPartName: { value: "Microprocessor A1", style: "" },
    supplierName: { value: "TechSupply Co.", style: "" },
    totalOrderQuantity: { value: 1000, style: "font-weight: bold;" },
    samplingSize: { value: 50, style: "" },
    totalOK: { value: 48, style: "color: #28a745;" },
    totalNOK: { value: 2, style: "color: #dc3545;" },
    createdAt: { value: "2023-07-01T10:30:00", style: "" },
  },
  {
    inspectionStatus: { value: "ONGOING", style: "color: #ffc107; font-weight: bold;" },
    inspectionId: { value: "INS-126", style: "color: #28a745; text-decoration: underline;" },
    lotStatusVerdict: { value: "IN_PROGRESS", style: "background-color: #17a2b8; color: white; padding: 2px 5px; border-radius: 3px;" },
    icPartName: { value: "Memory Module B2", style: "" },
    supplierName: { value: "ChipMakers Inc.", style: "" },
    totalOrderQuantity: { value: 5000, style: "font-weight: bold;" },
    samplingSize: { value: 100, style: "" },
    totalOK: { value: 95, style: "color: #28a745;" },
    totalNOK: { value: 5, style: "color: #dc3545;" },
    createdAt: { value: "2023-07-02T14:45:00", style: "" },
  },
  {
    inspectionStatus: { value: "SUBMITTED", style: "color: #28a745; font-weight: bold;" },
    inspectionId: { value: "INS-127", style: "color: #28a745; text-decoration: underline;" },
    lotStatusVerdict: { value: "APPROVED", style: "background-color: #28a745; color: white; padding: 2px 5px; border-radius: 3px;" },
    icPartName: { value: "GPU C3", style: "" },
    supplierName: { value: "GraphicsTech Ltd.", style: "" },
    totalOrderQuantity: { value: 2000, style: "font-weight: bold;" },
    samplingSize: { value: 75, style: "" },
    totalOK: { value: 75, style: "color: #28a745;" },
    totalNOK: { value: 0, style: "color: #28a745;" },
    createdAt: { value: "2023-07-03T09:15:00", style: "" },
  },
  {
    inspectionStatus: { value: "OPEN", style: "color: #007bff; font-weight: bold;" },
    inspectionId: { value: "INS-128", style: "color: #28a745; text-decoration: underline;" },
    lotStatusVerdict: { value: "PENDING", style: "background-color: #ffc107; padding: 2px 5px; border-radius: 3px;" },
    icPartName: { value: "Power Management IC D4", style: "" },
    supplierName: { value: "PowerChip Solutions", style: "" },
    totalOrderQuantity: { value: 3000, style: "font-weight: bold;" },
    samplingSize: { value: 80, style: "" },
    totalOK: { value: 78, style: "color: #28a745;" },
    totalNOK: { value: 2, style: "color: #dc3545;" },
    createdAt: { value: "2023-07-04T11:20:00", style: "" },
  },
  {
    inspectionStatus: { value: "ONGOING", style: "color: #ffc107; font-weight: bold;" },
    inspectionId: { value: "INS-129", style: "color: #28a745; text-decoration: underline;" },
    lotStatusVerdict: { value: "IN_PROGRESS", style: "background-color: #17a2b8; color: white; padding: 2px 5px; border-radius: 3px;" },
    icPartName: { value: "Sensor Array E5", style: "" },
    supplierName: { value: "SensorTech Industries", style: "" },
    totalOrderQuantity: { value: 4000, style: "font-weight: bold;" },
    samplingSize: { value: 90, style: "" },
    totalOK: { value: 88, style: "color: #28a745;" },
    totalNOK: { value: 2, style: "color: #dc3545;" },
    createdAt: { value: "2023-07-05T16:30:00", style: "" },
  },
  {
    inspectionStatus: { value: "SUBMITTED", style: "color: #28a745; font-weight: bold;" },
    inspectionId: { value: "INS-130", style: "color: #28a745; text-decoration: underline;" },
    lotStatusVerdict: { value: "REJECTED", style: "background-color: #dc3545; color: white; padding: 2px 5px; border-radius: 3px;" },
    icPartName: { value: "FPGA F6", style: "" },
    supplierName: { value: "LogicDesign Co.", style: "" },
    totalOrderQuantity: { value: 1500, style: "font-weight: bold;" },
    samplingSize: { value: 60, style: "" },
    totalOK: { value: 55, style: "color: #28a745;" },
    totalNOK: { value: 5, style: "color: #dc3545;" },
    createdAt: { value: "2023-07-06T13:45:00", style: "" },
  },
  {
    inspectionStatus: { value: "OPEN", style: "color: #007bff; font-weight: bold;" },
    inspectionId: { value: "INS-131", style: "color: #28a745; text-decoration: underline;" },
    lotStatusVerdict: { value: "PENDING", style: "background-color: #ffc107; padding: 2px 5px; border-radius: 3px;" },
    icPartName: { value: "Microcontroller G7", style: "" },
    supplierName: { value: "ControlSystems Ltd.", style: "" },
    totalOrderQuantity: { value: 6000, style: "font-weight: bold;" },
    samplingSize: { value: 120, style: "" },
    totalOK: { value: 118, style: "color: #28a745;" },
    totalNOK: { value: 2, style: "color: #dc3545;" },
    createdAt: { value: "2023-07-07T10:00:00", style: "" },
  },
  {
    inspectionStatus: { value: "ONGOING", style: "color: #ffc107; font-weight: bold;" },
    inspectionId: { value: "INS-132", style: "color: #28a745; text-decoration: underline;" },
    lotStatusVerdict: { value: "IN_PROGRESS", style: "background-color: #17a2b8; color: white; padding: 2px 5px; border-radius: 3px;" },
    icPartName: { value: "ADC H8", style: "" },
    supplierName: { value: "SignalProcess Inc.", style: "" },
    totalOrderQuantity: { value: 2500, style: "font-weight: bold;" },
    samplingSize: { value: 70, style: "" },
    totalOK: { value: 68, style: "color: #28a745;" },
    totalNOK: { value: 2, style: "color: #dc3545;" },
    createdAt: { value: "2023-07-08T15:20:00", style: "" },
  },
  {
    inspectionStatus: { value: "SUBMITTED", style: "color: #28a745; font-weight: bold;" },
    inspectionId: { value: "INS-133", style: "color: #28a745; text-decoration: underline;" },
    lotStatusVerdict: { value: "APPROVED", style: "background-color: #28a745; color: white; padding: 2px 5px; border-radius: 3px;" },
    icPartName: { value: "DAC I9", style: "" },
    supplierName: { value: "AnalogTech Co.", style: "" },
    totalOrderQuantity: { value: 3500, style: "font-weight: bold;" },
    samplingSize: { value: 85, style: "" },
    totalOK: { value: 85, style: "color: #28a745;" },
    totalNOK: { value: 0, style: "color: #28a745;" },
    createdAt: { value: "2023-07-09T11:30:00", style: "" },
  },
  {
    inspectionStatus: { value: "OPEN", style: "color: #007bff; font-weight: bold;" },
    inspectionId: { value: "INS-134", style: "color: #28a745; text-decoration: underline;" },
    lotStatusVerdict: { value: "PENDING", style: "background-color: #ffc107; padding: 2px 5px; border-radius: 3px;" },
    icPartName: { value: "RF Transceiver J10", style: "" },
    supplierName: { value: "WirelessSolutions Ltd.", style: "" },
    totalOrderQuantity: { value: 1800, style: "font-weight: bold;" },
    samplingSize: { value: 65, style: "" },
    totalOK: { value: 63, style: "color: #28a745;" },
    totalNOK: { value: 2, style: "color: #dc3545;" },
    createdAt: { value: "2023-07-10T14:00:00", style: "" },
  },
  {
    inspectionStatus: { value: "ONGOING", style: "color: #ffc107; font-weight: bold;" },
    inspectionId: { value: "INS-135", style: "color: #28a745; text-decoration: underline;" },
    lotStatusVerdict: { value: "IN_PROGRESS", style: "background-color: #17a2b8; color: white; padding: 2px 5px; border-radius: 3px;" },
    icPartName: { value: "EEPROM K11", style: "" },
    supplierName: { value: "MemoryTech Inc.", style: "" },
    totalOrderQuantity: { value: 4500, style: "font-weight: bold;" },
    samplingSize: { value: 95, style: "" },
    totalOK: { value: 92, style: "color: #28a745;" },
    totalNOK: { value: 3, style: "color: #dc3545;" },
    createdAt: { value: "2023-07-11T09:45:00", style: "" },
  },
  {
    inspectionStatus: { value: "SUBMITTED", style: "color: #28a745; font-weight: bold;" },
    inspectionId: { value: "INS-136", style: "color: #28a745; text-decoration: underline;" },
    lotStatusVerdict: { value: "APPROVED", style: "background-color: #28a745; color: white; padding: 2px 5px; border-radius: 3px;" },
    icPartName: { value: "Op-Amp L12", style: "" },
    supplierName: { value: "AnalogCircuits Co.", style: "" },
    totalOrderQuantity: { value: 5500, style: "font-weight: bold;" },
    samplingSize: { value: 110, style: "" },
    totalOK: { value: 110, style: "color: #28a745;" },
    totalNOK: { value: 0, style: "color: #28a745;" },
    createdAt: { value: "2023-07-12T16:15:00", style: "" },
  },
  {
    inspectionStatus: { value: "OPEN", style: "color: #007bff; font-weight: bold;" },
    inspectionId: { value: "INS-137", style: "color: #28a745; text-decoration: underline;" },
    lotStatusVerdict: { value: "PENDING", style: "background-color: #ffc107; padding: 2px 5px; border-radius: 3px;" },
    icPartName: { value: "Voltage Regulator M13", style: "" },
    supplierName: { value: "PowerElectronics Ltd.", style: "" },
    totalOrderQuantity: { value: 2200, style: "font-weight: bold;" },
    samplingSize: { value: 72, style: "" },
    totalOK: { value: 70, style: "color: #28a745;" },
    totalNOK: { value: 2, style: "color: #dc3545;" },
    createdAt: { value: "2023-07-13T10:30:00", style: "" },
  },
  {
    inspectionStatus: { value: "ONGOING", style: "color: #ffc107; font-weight: bold;" },
    inspectionId: { value: "INS-138", style: "color: #28a745; text-decoration: underline;" },
    lotStatusVerdict: { value: "IN_PROGRESS", style: "background-color: #17a2b8; color: white; padding: 2px 5px; border-radius: 3px;" },
    icPartName: { value: "LED Driver N14", style: "" },
    supplierName: { value: "IlluminationTech Co.", style: "" },
    totalOrderQuantity: { value: 3800, style: "font-weight: bold;" },
    samplingSize: { value: 88, style: "" },
    totalOK: { value: 86, style: "color: #28a745;" },
    totalNOK: { value: 2, style: "color: #dc3545;" },
    createdAt: { value: "2023-07-14T13:00:00", style: "" },
  },
  {
    inspectionStatus: { value: "SUBMITTED", style: "color: #28a745; font-weight: bold;" },
    inspectionId: { value: "INS-139", style: "color: #28a745; text-decoration: underline;" },
    lotStatusVerdict: { value: "REJECTED", style: "background-color: #dc3545; color: white; padding: 2px 5px; border-radius: 3px;" },
    icPartName: { value: "Motor Controller O15", style: "" },
    supplierName: { value: "MotionControl Systems", style: "" },
    totalOrderQuantity: { value: 1200, style: "font-weight: bold;" },
    samplingSize: { value: 55, style: "" },
    totalOK: { value: 50, style: "color: #28a745;" },
    totalNOK: { value: 5, style: "color: #dc3545;" },
    createdAt: { value: "2023-07-15T15:45:00", style: "" },
  },
];
