export default [
  {
    inspectionStatus: "OPEN",
    inspectionId: "INS-125",
    lotStatusVerdict: "PENDING",
    icPartName: "Microprocessor A1",
    supplierName: "TechSupply Co.",
    totalOrderQuantity: 1000,
    samplingSize: 50,
    totalOK: 48,
    totalNOK: 2,
    createdAt: "2023-07-01T10:30:00",
  },
  {
    inspectionStatus: "ONGOING",
    inspectionId: "INS-126",
    lotStatusVerdict: "IN_PROGRESS",
    icPartName: "Memory Module B2",
    supplierName: "ChipMakers Inc.",
    totalOrderQuantity: 5000,
    samplingSize: 100,
    totalOK: 95,
    totalNOK: 5,
    createdAt: "2023-07-02T14:45:00",
  },
  {
    inspectionStatus: "SUBMITTED",
    inspectionId: "INS-127",
    lotStatusVerdict: "APPROVED",
    icPartName: "GPU C3",
    supplierName: "GraphicsTech Ltd.",
    totalOrderQuantity: 2000,
    samplingSize: 75,
    totalOK: 75,
    totalNOK: 0,
    createdAt: "2023-07-03T09:15:00",
  },
  {
    inspectionStatus: "OPEN",
    inspectionId: "INS-128",
    lotStatusVerdict: "PENDING",
    icPartName: "Power Management IC D4",
    supplierName: "PowerChip Solutions",
    totalOrderQuantity: 3000,
    samplingSize: 80,
    totalOK: 78,
    totalNOK: 2,
    createdAt: "2023-07-04T11:20:00",
  },
  {
    inspectionStatus: "ONGOING",
    inspectionId: "INS-129",
    lotStatusVerdict: "IN_PROGRESS",
    icPartName: "Sensor Array E5",
    supplierName: "SensorTech Industries",
    totalOrderQuantity: 4000,
    samplingSize: 90,
    totalOK: 88,
    totalNOK: 2,
    createdAt: "2023-07-05T16:30:00",
  },
  {
    inspectionStatus: "SUBMITTED",
    inspectionId: "INS-130",
    lotStatusVerdict: "REJECTED",
    icPartName: "FPGA F6",
    supplierName: "LogicDesign Co.",
    totalOrderQuantity: 1500,
    samplingSize: 60,
    totalOK: 55,
    totalNOK: 5,
    createdAt: "2023-07-06T13:45:00",
  },
  {
    inspectionStatus: "OPEN",
    inspectionId: "INS-131",
    lotStatusVerdict: "PENDING",
    icPartName: "Microcontroller G7",
    supplierName: "ControlSystems Ltd.",
    totalOrderQuantity: 6000,
    samplingSize: 120,
    totalOK: 118,
    totalNOK: 2,
    createdAt: "2023-07-07T10:00:00",
  },
  {
    inspectionStatus: "ONGOING",
    inspectionId: "INS-132",
    lotStatusVerdict: "IN_PROGRESS",
    icPartName: "ADC H8",
    supplierName: "SignalProcess Inc.",
    totalOrderQuantity: 2500,
    samplingSize: 70,
    totalOK: 68,
    totalNOK: 2,
    createdAt: "2023-07-08T15:20:00",
  },
  {
    inspectionStatus: "SUBMITTED",
    inspectionId: "INS-133",
    lotStatusVerdict: "APPROVED",
    icPartName: "DAC I9",
    supplierName: "AnalogTech Co.",
    totalOrderQuantity: 3500,
    samplingSize: 85,
    totalOK: 85,
    totalNOK: 0,
    createdAt: "2023-07-09T11:30:00",
  },
  {
    inspectionStatus: "OPEN",
    inspectionId: "INS-134",
    lotStatusVerdict: "PENDING",
    icPartName: "RF Transceiver J10",
    supplierName: "WirelessSolutions Ltd.",
    totalOrderQuantity: 1800,
    samplingSize: 65,
    totalOK: 63,
    totalNOK: 2,
    createdAt: "2023-07-10T14:00:00",
  },
  {
    inspectionStatus: "ONGOING",
    inspectionId: "INS-135",
    lotStatusVerdict: "IN_PROGRESS",
    icPartName: "EEPROM K11",
    supplierName: "MemoryTech Inc.",
    totalOrderQuantity: 4500,
    samplingSize: 95,
    totalOK: 92,
    totalNOK: 3,
    createdAt: "2023-07-11T09:45:00",
  },
  {
    inspectionStatus: "SUBMITTED",
    inspectionId: "INS-136",
    lotStatusVerdict: "APPROVED",
    icPartName: "Op-Amp L12",
    supplierName: "AnalogCircuits Co.",
    totalOrderQuantity: 5500,
    samplingSize: 110,
    totalOK: 110,
    totalNOK: 0,
    createdAt: "2023-07-12T16:15:00",
  },
  {
    inspectionStatus: "OPEN",
    inspectionId: "INS-137",
    lotStatusVerdict: "PENDING",
    icPartName: "Voltage Regulator M13",
    supplierName: "PowerElectronics Ltd.",
    totalOrderQuantity: 2200,
    samplingSize: 72,
    totalOK: 70,
    totalNOK: 2,
    createdAt: "2023-07-13T10:30:00",
  },
  {
    inspectionStatus: "ONGOING",
    inspectionId: "INS-138",
    lotStatusVerdict: "IN_PROGRESS",
    icPartName: "LED Driver N14",
    supplierName: "IlluminationTech Co.",
    totalOrderQuantity: 3800,
    samplingSize: 88,
    totalOK: 86,
    totalNOK: 2,
    createdAt: "2023-07-14T13:00:00",
  },
  {
    inspectionStatus: "SUBMITTED",
    inspectionId: "INS-139",
    lotStatusVerdict: "REJECTED",
    icPartName: "Motor Controller O15",
    supplierName: "MotionControl Systems",
    totalOrderQuantity: 1200,
    samplingSize: 55,
    totalOK: 50,
    totalNOK: 5,
    createdAt: "2023-07-15T15:45:00",
  },
];
